name: Build and Push Wordsmith Images

on:
  pull_request:
    types: [labeled]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: web
            dockerfile: web/Dockerfile
            context: ./web
          - service: words
            dockerfile: words/Dockerfile
            context: ./words
          - service: db
            dockerfile: db/Dockerfile
            context: ./db
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/wordsmith-${{ matrix.service }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/wordsmith-${{ matrix.service }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/wordsmith-${{ matrix.service }}:pr-${{ github.event.pull_request.number }}
